services:
  prod:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/teste

  staging:
    build:
      context: .
    ports:
      - 8081:8080
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/teste

#   db:
#     image: mysql
#     volumes:
#       - db-data:/var/lib/mysql/
#     environment:
# #      - MYSQL_DB=
# #      - MYSQL_USER=
# #      - MYSQL_PASSWORD=
#     ports:
#       - 3306:3306
