name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  REGISTRY: docker.io
  IMAGE_NAME: bodedimitri/my-java-app 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn clean package
        working-directory: Faculdade

      - name: Verify JAR generation
        run: ls -lh Faculdade/target

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: Faculdade/target/*.jar

  docker-build-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/ # Changed path to 'target/'

      - name: List downloaded artifact
        run: ls -lh target/

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          # Extract the JAR filename.  Crucial for robustness.
          JAR_FILE=$(find target/ -name "*.jar" -printf "%f\n")
          TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $REGISTRY/$IMAGE_NAME:$TAG -f Dockerfile . # Corrected Dockerfile path
          docker push $REGISTRY/$IMAGE_NAME:$TAG
          docker tag $REGISTRY/$IMAGE_NAME:$TAG $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest

  deploy-staging:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy to Staging
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_SSH }} << EOF
            docker pull $REGISTRY/$IMAGE_NAME:latest
            docker stop my-java-app || true
            docker rm my-java-app || true
            docker run -d --name my-java-app -p 8080:8080 -e PROFILE=stg $REGISTRY/$IMAGE_NAME:latest
          EOF

  deploy-production:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PRODUCTION_SSH }} << EOF
            docker pull $REGISTRY/$IMAGE_NAME:latest
            docker stop my-java-app || true
            docker rm my-java-app || true
            docker run -d --name my-java-app -p 8080:8080 -e PROFILE=prd $REGISTRY/$IMAGE_NAME:latest
          EOF
